export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const CONTACT_FILTER = 'CONTACT_FILTER';